# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63daff098c7ef2a714279fcb3829b4b46edeac26d07674325e626e20a8b2ca47a4baeecbea133e608488e765d6598b7c8018418d4fc96c12f6dccf0d69aaff18

test:
  secret_key_base: 43e58e2fb13e944f77963c7948dff069b8dfe3282ee406cf4bde85df63313215cc3ff6510d6a0d57a24c07a1ae921d2efd4718d08ad1c4e6b1f6d2ca3a1471d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
